version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      react-family:
        patterns:
          - "@types/react"
          - "@types/react-dom"
          - "react"
          - "react-dom"
          - "next"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
