import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import BaseLayout from 'beautiful-next-theme/src/layouts/BaseLayout'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<React.PropsWithChildren> = ({ children }) => {
  return <BaseLayout config={{}} page={{}}>{children}</BaseLayout>
}

export default RootLayout
