import type { GetStaticProps, InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'


const getPostsFromMarkdown = () => {
  const files = fs.readdirSync(path.join('posts'))

  const posts = files.map(filename => {
    const markdownWithMeta = fs.readFileSync(path.join('posts', filename), 'utf-8')
    const { data: frontMatter } = matter(markdownWithMeta)
    return {
      frontMatter,
      slug: filename.split('.')[0]
    }
  })

  return posts
}
type Posts = ReturnType<typeof getPostsFromMarkdown>

export const getStaticProps = async () => {
  return {
    props: {
      posts: getPostsFromMarkdown()
    }
  }
}

type StaticProps = InferGetStaticPropsType<typeof getStaticProps>


const Home: NextPage<StaticProps> = ({ posts }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image 
          className={styles.profileImage}
          src="/images/profile.jpeg" // Route of the image file
          height={144} // Desired size with correct aspect ratio
          width={144} // Desired size with correct aspect ratio
          alt="Giorgia's profile"
        />
        
        <h1 className={styles.title}>
          {"Welcome to Giorgia's notes"}
        </h1>
        <p>Find here a list of my posts</p>
      </main>

      <div className="mt-5">
      {posts.map((post, index) => (
        <Link href={'/blog/' + post.slug} passHref key={index}>
          <div className="card mb-3 pointer" style={{ maxWidth: '540px' }}>
            <div className="row g-0">
              <div className="col-md-8">
                <div className="card-body">
                <Link href={'/posts/' + post.slug} >
                  <a  href={'/posts/' + post.slug}>
                    <h5 className="card-title">{'/posts/' + post.slug}</h5>
                  </a>
                  
                </Link>
                  
                  <h5 className="card-title">{post.frontMatter.title}</h5>
                  <p className="card-text">{post.frontMatter.description}</p>
                  <p className="card-text">
                    <small className="text-muted">{post.frontMatter.date}</small>
                  </p>
                </div>
              </div>
              <div className="col-md-4 m-auto">
                <Image
                  src={post.frontMatter.thumbnailUrl}
                  className="img-fluid mt-1 rounded-start"
                  alt="thumbnail"
                  width={500}
                  height={400}
                  objectFit="cover"
                />
              </div>
            </div>
          </div>
        </Link>
      ))}
    </div>

      <footer className={styles.footer}>
        <p>Ⓒ Giorgia Faedda - 2022</p>
      </footer>
    </div>
  )
}



export default Home
