name: Beautiful Jekyll CI
on: [push, pull_request]
jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt install ruby ruby-dev ruby-bundler
          make install
      - name: Build the site
        run: |
          echo "building version $GIT_HASH"
          ruby _scripts/generate_env_config.rb
          cat _env.yml
          make build
        env: # Export secret as an environment variable
          GOOGLE_ANALYTICS_GTAG: ${{ secrets.GOOGLE_ANALYTICS_GTAG }}
          PAGES_REPO_NWO: ${{ github.repository }}
          GIT_HASH: ${{ github.sha }}
